# Generated by Django 4.2.3 on 2023-07-27 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("taggit", "0005_auto_20220424_2025"),
        ("food", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodComments",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("comment", models.CharField(max_length=256, verbose_name="评论内容")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="评论时间"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FoodFavor",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="收藏时间"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FoodPurchase",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("rating", models.IntegerField(default=0, verbose_name="评分")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="购买时间"),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="UsrInfo",
        ),
        migrations.RemoveField(
            model_name="foodinfo",
            name="foodName",
        ),
        migrations.RemoveField(
            model_name="foodinfo",
            name="parentName",
        ),
        migrations.AddField(
            model_name="foodinfo",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="创建时间",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="foodinfo",
            name="food_name",
            field=models.CharField(
                default=django.utils.timezone.now,
                max_length=128,
                unique=True,
                verbose_name="菜品名",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="foodinfo",
            name="rating",
            field=models.FloatField(default=0.0, verbose_name="评分"),
        ),
        migrations.AddField(
            model_name="foodinfo",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="标签",
            ),
        ),
        migrations.AlterField(
            model_name="foodinfo",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="foodinfo",
            name="purchases",
            field=models.IntegerField(default=0, verbose_name="购买量"),
        ),
        migrations.AlterField(
            model_name="foodinfo",
            name="stars",
            field=models.IntegerField(default=0, verbose_name="收藏量"),
        ),
        migrations.AddField(
            model_name="foodpurchase",
            name="food",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="food.foodinfo",
                verbose_name="菜品",
            ),
        ),
        migrations.AddField(
            model_name="foodpurchase",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AddField(
            model_name="foodfavor",
            name="food",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="food.foodinfo",
                verbose_name="菜品",
            ),
        ),
        migrations.AddField(
            model_name="foodfavor",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AddField(
            model_name="foodcomments",
            name="food",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="food.foodinfo",
                verbose_name="菜品",
            ),
        ),
        migrations.AddField(
            model_name="foodcomments",
            name="replied",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="food.foodcomments",
                verbose_name="回复",
            ),
        ),
        migrations.AddField(
            model_name="foodcomments",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
    ]
