# Generated by Django 4.2.3 on 2023-07-29 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodpurchase",
            name="date",
            field=models.CharField(
                blank=True, default="", max_length=128, verbose_name="购买日期"
            ),
        ),
        migrations.AddField(
            model_name="foodpurchase",
            name="time",
            field=models.CharField(
                blank=True, default="", max_length=128, verbose_name="餐点"
            ),
        ),
        migrations.AlterField(
            model_name="foodinfo",
            name="counter",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="food.counterinfo",
                verbose_name="柜台",
            ),
        ),
        migrations.AlterField(
            model_name="foodinfo",
            name="region",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="food.regioninfo",
                verbose_name="地区",
            ),
        ),
    ]
