# Generated by Django 4.2.3 on 2023-07-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0002_foodcomments_foodfavor_foodpurchase_delete_usrinfo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodinfo",
            name="photo_url",
            field=models.CharField(default="", max_length=256, verbose_name="图片地址"),
        ),
    ]
