# Generated by Django 4.2.3 on 2023-07-28 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0003_foodinfo_photo_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodinfo",
            name="price",
            field=models.CharField(max_length=64, verbose_name="价格"),
        ),
        migrations.CreateModel(
            name="TagFavor",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("tag", models.CharField(max_length=128, verbose_name="单标签")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="收藏时间"),
                ),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food.foodinfo",
                        verbose_name="菜品",
                    ),
                ),
            ],
        ),
    ]
