# Generated by Django 4.2.3 on 2023-07-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0004_alter_foodinfo_price_tagfavor"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodinfo",
            name="comments",
            field=models.IntegerField(default=0, verbose_name="评论数"),
        ),
    ]
