# Generated by Django 4.2.3 on 2023-07-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0005_foodinfo_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodcomments",
            name="is_anonymous",
            field=models.BooleanField(blank=True, default=False, verbose_name="是否匿名"),
        ),
    ]
